import {GREEN, RED, BLUE, GREEN_LIGHT, RED_LIGHT, BLUE_LIGHT} from './Colors'
export const SEAT_TYPE = {
	WINDOW: 'W',
	MIDDLE: 'M',
	AISLE: 'A'
}

export const SEAT_BG_COLOR = {
	[SEAT_TYPE.WINDOW]: GREEN_LIGHT,
	[SEAT_TYPE.MIDDLE]: RED_LIGHT,
	[SEAT_TYPE.AISLE]: BLUE_LIGHT,
}

export const SEAT_BORDER_COLOR = {
	[SEAT_TYPE.WINDOW]: GREEN,
	[SEAT_TYPE.MIDDLE]: RED,
	[SEAT_TYPE.AISLE]: BLUE,
}
